# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
particle minecraft:soul ~ ~1 ~ .1 .1 .1 .04 1
particle minecraft:soul ~ ~1 ~ .1 .1 .1 .04 1
playsound minecraft:entity.skeleton.step hostile @a ~ ~ ~ 0.6 0.5