# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rend_fallen_tether.root] run return 0
execute on passengers if entity @s[tag=aj.rend_fallen_tether.data] unless data entity @s {data:{rigHash: '3ad60279d49b97f10a4dbeb7ff6f1286e41934a713a4991373a546998135b654'}} on vehicle run function animated_java:rend_fallen_tether/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1