# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rend_fallen_tether.root] run return 0
execute on passengers if entity @s[tag=aj.rend_fallen_tether.data] unless data entity @s {data:{rigHash: 'cd4a34e8a4b0efc955ecd2926d1b98c189421a5caceb7e38acd88f18ce68f639'}} on vehicle run function animated_java:rend_fallen_tether/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1