# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.rend_fallen_tether.root] run return 0
execute on passengers if entity @s[tag=aj.rend_fallen_tether.data] unless data entity @s {data:{rigHash: '9280221ff2e31e782c35cb93a0c4c3c1c21335050b4e4ec0dae6d7cc68a5c2b8'}} on vehicle run function animated_java:rend_fallen_tether/root/zzz/0
scoreboard players set @s aj.is_rig_loaded 1