# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.rise_0.frame dummy
scoreboard objectives add aj.rise_1.frame dummy