### Particle Image Function
### Version: 1.0.4
### Width: 16
### Height: 16
### ParticleType: dust

### This file was generated by Kemo431's Particle-Converter.
### Download Link: https://github.com/kemo14331/Particle-Converter

particle minecraft:dust{color:[0.98,0.83,0.25],scale:1} ^2 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.85,0.25],scale:1} ^2 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.85,0.26],scale:1} ^2 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.85,0.25],scale:1} ^2 ^0 ^0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.68,0.22],scale:1} ^1.75 ^0 ^-1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.77,0.24],scale:1} ^1.75 ^0 ^-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.78,0.25],scale:1} ^1.75 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.67,0.22],scale:1} ^1.75 ^0 ^0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.58,0.21],scale:1} ^1.5 ^0 ^-1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.53,0.16],scale:1} ^1.5 ^0 ^-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.42,0.13],scale:1} ^1.5 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.46,0.18],scale:1} ^1.5 ^0 ^1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.49,0.18],scale:1} ^1.25 ^0 ^-1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.53,0.16],scale:1} ^1.25 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.39,0.14],scale:1} ^1.25 ^0 ^1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.38,0.17],scale:1} ^1 ^0 ^-1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.63,0.19],scale:1} ^1 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.69,0.21],scale:1} ^1 ^0 ^1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.5,0.19],scale:1} ^0.75 ^0 ^-1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.82,0.24],scale:1} ^0.75 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.67,0.2],scale:1} ^0.75 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.83,0.25],scale:1} ^0.75 ^0 ^1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.73,0.24],scale:1} ^0.75 ^0 ^1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.64,0.22],scale:1} ^0.5 ^0 ^-2 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.86,0.25],scale:1} ^0.5 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.78,0.23],scale:1} ^0.5 ^0 ^0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.82,0.25],scale:1} ^0.5 ^0 ^1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.68,0.23],scale:1} ^0.5 ^0 ^1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.71,0.23],scale:1} ^0.25 ^0 ^-2 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.87,0.25],scale:1} ^0.25 ^0 ^-1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.87,0.25],scale:1} ^0.25 ^0 ^-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.83,0.24],scale:1} ^0.25 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.87,0.26],scale:1} ^0.25 ^0 ^1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.55,0.22],scale:1} ^0.25 ^0 ^1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.8,0.24],scale:1} ^0 ^0 ^-2 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.84,0.25],scale:1} ^0 ^0 ^-1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.87,0.26],scale:1} ^0 ^0 ^-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.85,0.25],scale:1} ^0 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.88,0.26],scale:1} ^0 ^0 ^0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.42,0.16],scale:1} ^0 ^0 ^1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.81,0.24],scale:1} ^-0.25 ^0 ^-2 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.82,0.24],scale:1} ^-0.25 ^0 ^-1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.85,0.25],scale:1} ^-0.25 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.88,0.26],scale:1} ^-0.25 ^0 ^0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.92,0.32,0.12],scale:1} ^-0.25 ^0 ^1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.61,0.2],scale:1} ^-0.5 ^0 ^-1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.72,0.22],scale:1} ^-0.5 ^0 ^-1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.77,0.23],scale:1} ^-0.5 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.98,0.89,0.26],scale:1} ^-0.5 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.36,0.13],scale:1} ^-0.5 ^0 ^1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.49,0.17],scale:1} ^-0.75 ^0 ^-1.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.53,0.18],scale:1} ^-0.75 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.36,0.17],scale:1} ^-0.75 ^0 ^1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.4,0.16],scale:1} ^-1 ^0 ^-1.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.51,0.17],scale:1} ^-1 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.71,0.22],scale:1} ^-1 ^0 ^1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.48,0.18],scale:1} ^-1.25 ^0 ^-1.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.31,0.11],scale:1} ^-1.25 ^0 ^0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.34,0.11],scale:1} ^-1.25 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.82,0.25],scale:1} ^-1.25 ^0 ^1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.57,0.21],scale:1} ^-1.5 ^0 ^-1 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.71,0.23],scale:1} ^-1.5 ^0 ^-0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.93,0.46,0.14],scale:1} ^-1.5 ^0 ^0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.61,0.18],scale:1} ^-1.5 ^0 ^0.75 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.97,0.82,0.25],scale:1} ^-1.75 ^0 ^-0.5 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.96,0.76,0.23],scale:1} ^-1.75 ^0 ^-0.25 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.95,0.69,0.2],scale:1} ^-1.75 ^0 ^0 0 0 0 0 1 force @a
particle minecraft:dust{color:[0.94,0.57,0.16],scale:1} ^-1.75 ^0 ^0.25 0 0 0 0 1 force @a
